"""Unit tests for CodeGenerator.assemble."""

import pytest
from src.worker.engine.codegen import CodeGenerator
from src.worker.engine.models import BlockType, GeneratedBlock, MacroVar, SASBlock


def _sas_block(
    block_type: BlockType = BlockType.DATA_STEP,
    source_file: str = "etl.sas",
    start_line: int = 1,
    end_line: int = 5,
    raw_sas: str = "data out; set in; run;",
) -> SASBlock:
    return SASBlock(
        block_type=block_type,
        source_file=source_file,
        start_line=start_line,
        end_line=end_line,
        raw_sas=raw_sas,
    )


def _gen_block(
    python_code: str = "result = df.copy()  # SAS: etl.sas:1",
    is_untranslatable: bool = False,
    **sas_kwargs: object,
) -> GeneratedBlock:
    return GeneratedBlock(
        source_block=_sas_block(**sas_kwargs),  # type: ignore[arg-type]
        python_code=python_code,
        is_untranslatable=is_untranslatable,
    )


@pytest.fixture()
def codegen() -> CodeGenerator:
    return CodeGenerator()


def test_assemble_contains_provenance_header(codegen: CodeGenerator) -> None:
    output = codegen.assemble([_gen_block()])
    assert "Generated by Rosetta Decode" in output
    assert "etl.sas" in output


def test_assemble_contains_block_code(codegen: CodeGenerator) -> None:
    output = codegen.assemble([_gen_block(python_code="x = 1  # SAS: etl.sas:1")])
    assert "x = 1" in output


def test_assemble_includes_import_pandas(codegen: CodeGenerator) -> None:
    output = codegen.assemble([_gen_block()])
    assert "import pandas as pd" in output


def test_assemble_section_header_format(codegen: CodeGenerator) -> None:
    output = codegen.assemble([_gen_block()])
    assert "DATA_STEP" in output
    assert "etl.sas:1" in output


def test_assemble_untranslatable_block_has_warning(codegen: CodeGenerator) -> None:
    block = _gen_block(
        python_code="# SAS-UNTRANSLATABLE: PROC REPORT not supported",
        is_untranslatable=True,
        block_type=BlockType.UNTRANSLATABLE,
    )
    output = codegen.assemble([block])
    assert "UNTRANSLATABLE" in output
    assert "WARNING" in output


def test_assemble_multiple_blocks_in_order(codegen: CodeGenerator) -> None:
    b1 = _gen_block(python_code="step1 = 1  # SAS: etl.sas:1", start_line=1, end_line=3)
    b2 = _gen_block(python_code="step2 = 2  # SAS: etl.sas:5", start_line=5, end_line=8)
    output = codegen.assemble([b1, b2])
    assert output.index("step1") < output.index("step2")


def test_assemble_deduplicates_source_files(codegen: CodeGenerator) -> None:
    b1 = _gen_block(source_file="a.sas")
    b2 = _gen_block(source_file="a.sas", start_line=10, end_line=15)
    output = codegen.assemble([b1, b2])
    # "a.sas" should appear once in the header line, not twice
    header_line = next(line for line in output.splitlines() if "Source files:" in line)
    assert header_line.count("a.sas") == 1


def test_assemble_empty_blocks_returns_header_only(codegen: CodeGenerator) -> None:
    output = codegen.assemble([])
    assert "Generated by Rosetta Decode" in output
    assert "import pandas as pd" in output


@pytest.fixture()
def minimal_block() -> GeneratedBlock:
    return GeneratedBlock(
        source_block=SASBlock(
            block_type=BlockType.DATA_STEP,
            source_file="test.sas",
            start_line=1,
            end_line=3,
            raw_sas="DATA out; SET inp; RUN;",
        ),
        python_code="out = inp.copy()  # SAS: test.sas:1",
        is_untranslatable=False,
    )


def test_assemble_with_macro_vars_prepends_constants(
    codegen: CodeGenerator, minimal_block: GeneratedBlock
) -> None:
    mv = MacroVar(name="THRESHOLD", raw_value="100", source_file="x.sas", line=1)
    output = codegen.assemble([minimal_block], macro_vars=[mv])
    assert "THRESHOLD = 100" in output
    assert "# SAS: x.sas:1" in output
    # Constants section must appear before the pandas import
    assert output.index("THRESHOLD") < output.index("import pandas")


def test_assemble_without_macro_vars_unchanged(
    codegen: CodeGenerator, minimal_block: GeneratedBlock
) -> None:
    output = codegen.assemble([minimal_block])
    assert "# ── Macro constants" not in output
    assert "import pandas as pd" in output
