"""Unit tests for CodeGenerator.assemble and assemble_flat."""

import pytest
from src.worker.engine.codegen import CodeGenerator
from src.worker.engine.models import BlockType, GeneratedBlock, MacroVar, SASBlock


def _sas_block(
    block_type: BlockType = BlockType.DATA_STEP,
    source_file: str = "etl.sas",
    start_line: int = 1,
    end_line: int = 5,
    raw_sas: str = "data out; set in; run;",
) -> SASBlock:
    return SASBlock(
        block_type=block_type,
        source_file=source_file,
        start_line=start_line,
        end_line=end_line,
        raw_sas=raw_sas,
    )


def _gen_block(
    python_code: str = "result = df.copy()  # SAS: etl.sas:1",
    is_untranslatable: bool = False,
    confidence: str = "high",
    **sas_kwargs: object,
) -> GeneratedBlock:
    return GeneratedBlock(
        source_block=_sas_block(**sas_kwargs),  # type: ignore[arg-type]
        python_code=python_code,
        is_untranslatable=is_untranslatable,
        confidence=confidence,
    )


@pytest.fixture()
def codegen() -> CodeGenerator:
    return CodeGenerator()


# ── assemble_flat (legacy single-string) ─────────────────────────────────────


def test_assemble_flat_contains_provenance_header(codegen: CodeGenerator) -> None:
    output = codegen.assemble_flat([_gen_block()])
    assert "Generated by Rosetta Decode" in output
    assert "etl.sas" in output


def test_assemble_flat_contains_block_code(codegen: CodeGenerator) -> None:
    output = codegen.assemble_flat([_gen_block(python_code="x = 1  # SAS: etl.sas:1")])
    assert "x = 1" in output


def test_assemble_flat_includes_import_pandas(codegen: CodeGenerator) -> None:
    output = codegen.assemble_flat([_gen_block()])
    assert "import pandas as pd" in output


def test_assemble_flat_section_header_format(codegen: CodeGenerator) -> None:
    output = codegen.assemble_flat([_gen_block()])
    assert "DATA_STEP" in output
    assert "etl.sas:1" in output


def test_assemble_flat_untranslatable_block_has_warning(codegen: CodeGenerator) -> None:
    block = _gen_block(
        python_code="# SAS-UNTRANSLATABLE: PROC REPORT not supported",
        is_untranslatable=True,
        block_type=BlockType.UNTRANSLATABLE,
    )
    output = codegen.assemble_flat([block])
    assert "UNTRANSLATABLE" in output
    assert "WARNING" in output


def test_assemble_flat_multiple_blocks_in_order(codegen: CodeGenerator) -> None:
    b1 = _gen_block(python_code="step1 = 1  # SAS: etl.sas:1", start_line=1, end_line=3)
    b2 = _gen_block(python_code="step2 = 2  # SAS: etl.sas:5", start_line=5, end_line=8)
    output = codegen.assemble_flat([b1, b2])
    assert output.index("step1") < output.index("step2")


def test_assemble_flat_deduplicates_source_files(codegen: CodeGenerator) -> None:
    b1 = _gen_block(source_file="a.sas")
    b2 = _gen_block(source_file="a.sas", start_line=10, end_line=15)
    output = codegen.assemble_flat([b1, b2])
    header_line = next(line for line in output.splitlines() if "Source files:" in line)
    assert header_line.count("a.sas") == 1


def test_assemble_flat_empty_blocks_returns_header_only(codegen: CodeGenerator) -> None:
    output = codegen.assemble_flat([])
    assert "Generated by Rosetta Decode" in output
    assert "import pandas as pd" in output


@pytest.fixture()
def minimal_block() -> GeneratedBlock:
    return GeneratedBlock(
        source_block=SASBlock(
            block_type=BlockType.DATA_STEP,
            source_file="test.sas",
            start_line=1,
            end_line=3,
            raw_sas="DATA out; SET inp; RUN;",
        ),
        python_code="out = inp.copy()  # SAS: test.sas:1",
        is_untranslatable=False,
    )


def test_assemble_flat_with_macro_vars_prepends_constants(
    codegen: CodeGenerator, minimal_block: GeneratedBlock
) -> None:
    mv = MacroVar(name="THRESHOLD", raw_value="100", source_file="x.sas", line=1)
    output = codegen.assemble_flat([minimal_block], macro_vars=[mv])
    assert "THRESHOLD = 100" in output
    assert "# SAS: x.sas:1" in output
    assert output.index("THRESHOLD") < output.index("import pandas")


def test_assemble_flat_without_macro_vars_unchanged(
    codegen: CodeGenerator, minimal_block: GeneratedBlock
) -> None:
    output = codegen.assemble_flat([minimal_block])
    assert "# ── Macro constants" not in output
    assert "import pandas as pd" in output


# ── assemble (multi-file dict) ────────────────────────────────────────────────


def test_assemble_returns_dict(codegen: CodeGenerator) -> None:
    result = codegen.assemble([_gen_block()])
    assert isinstance(result, dict)


def test_assemble_emits_pipeline_py(codegen: CodeGenerator) -> None:
    result = codegen.assemble([_gen_block()])
    assert "pipeline.py" in result


def test_assemble_emits_module_for_each_sas_file(codegen: CodeGenerator) -> None:
    b1 = _gen_block(source_file="etl.sas")
    b2 = _gen_block(source_file="transforms.sas", start_line=1, end_line=5)
    result = codegen.assemble([b1, b2])
    assert "etl.py" in result
    assert "transforms.py" in result


def test_assemble_module_wraps_in_run_function(codegen: CodeGenerator) -> None:
    result = codegen.assemble([_gen_block()])
    assert "def run(dataframes: dict) -> dict:" in result["etl.py"]
    assert "return dataframes" in result["etl.py"]


def test_assemble_pipeline_imports_all_modules(codegen: CodeGenerator) -> None:
    b1 = _gen_block(source_file="etl.sas")
    b2 = _gen_block(source_file="transforms.sas", start_line=1, end_line=5)
    result = codegen.assemble([b1, b2])
    pipeline = result["pipeline.py"]
    assert "etl" in pipeline
    assert "transforms" in pipeline
    assert "etl.run(dataframes)" in pipeline
    assert "transforms.run(dataframes)" in pipeline


def test_assemble_pipeline_threads_dataframes(codegen: CodeGenerator) -> None:
    b1 = _gen_block(source_file="etl.sas")
    b2 = _gen_block(source_file="transforms.sas", start_line=1, end_line=5)
    result = codegen.assemble([b1, b2])
    pipeline = result["pipeline.py"]
    assert pipeline.index("etl.run") < pipeline.index("transforms.run")


def test_assemble_uncertain_module_has_warning_comment(codegen: CodeGenerator) -> None:
    block = _gen_block(confidence="medium")
    result = codegen.assemble([block])
    assert "UNCERTAIN blocks present" in result["etl.py"]


def test_assemble_high_confidence_module_no_warning(codegen: CodeGenerator) -> None:
    block = _gen_block(confidence="high")
    result = codegen.assemble([block])
    assert "UNCERTAIN blocks present" not in result["etl.py"]


def test_assemble_module_stem_from_path(codegen: CodeGenerator) -> None:
    block = _gen_block(source_file="subdir/etl.sas")
    result = codegen.assemble([block])
    assert "etl.py" in result


def test_assemble_module_contains_block_code(codegen: CodeGenerator) -> None:
    block = _gen_block(python_code="x = 42  # SAS: etl.sas:1")
    result = codegen.assemble([block])
    assert "x = 42" in result["etl.py"]


def test_assemble_with_macro_vars_in_module(
    codegen: CodeGenerator, minimal_block: GeneratedBlock
) -> None:
    mv = MacroVar(name="THRESHOLD", raw_value="100", source_file="x.sas", line=1)
    result = codegen.assemble([minimal_block], macro_vars=[mv])
    module = result["test.py"]
    assert "THRESHOLD = 100" in module


def test_assemble_empty_blocks_returns_only_pipeline(codegen: CodeGenerator) -> None:
    result = codegen.assemble([])
    assert list(result.keys()) == ["pipeline.py"]
