"""Code generator — assembles GeneratedBlocks into a single pipeline.py file.

Uses Jinja2 for the file-level template so the header and block stitching are
clearly separated from the translation logic.  The resulting file:

- Starts with a provenance header listing all source files
- Includes necessary imports (pandas)
- Renders each block in dependency order with its ``# SAS: <file>:<line>``
  provenance comment already embedded by the LLM
- Wraps untranslatable blocks in a clearly labelled comment section
"""

from dataclasses import dataclass
from datetime import UTC, datetime

from jinja2 import Environment, StrictUndefined
from src.worker.engine.models import GeneratedBlock, MacroVar

# ── Jinja2 template ───────────────────────────────────────────────────────────

_PIPELINE_TEMPLATE = """\
# Generated by Rosetta Decode — {{ generated_at }}
# Source files: {{ source_files | join(", ") }}
#
# WARNING: Review all # SAS-UNTRANSLATABLE sections before running in production.
{% if constants %}

# ── Macro constants ──────────────────────────────────────────────────────────
{% for c in constants %}
{{ c.name }} = {{ c.raw_value }}  # SAS: {{ c.source_file }}:{{ c.line }}
{% endfor %}
{% endif %}

import pandas as pd
{% for entry in entries %}

# ── {{ entry.header }}
{% if entry.block.is_untranslatable %}
# ┌─ UNTRANSLATABLE ────────────────────────────────────────────────────────┐
{{ entry.block.python_code }}
# └────────────────────────────────────────────────────────────────────────┘
{% else %}
{{ entry.block.python_code }}
{% endif %}
{% endfor %}
"""


@dataclass
class _BlockEntry:
    """Pairs a GeneratedBlock with a pre-computed single-line header."""

    header: str
    block: GeneratedBlock


def _make_env() -> Environment:
    """Return a Jinja2 environment with strict undefined checking."""
    return Environment(undefined=StrictUndefined, keep_trailing_newline=True)


def _block_header(block: GeneratedBlock) -> str:
    """Build the one-line section header for a block.

    Args:
        block: The generated block to label.

    Returns:
        Header string in the form ``TYPE — file:line``.
    """
    sb = block.source_block
    return f"{sb.block_type.value} — {sb.source_file}:{sb.start_line}"


# ── Public API ────────────────────────────────────────────────────────────────


class CodeGenerator:
    """Assembles a list of GeneratedBlocks into a complete Python pipeline file."""

    def __init__(self) -> None:
        """Initialise the Jinja2 environment and compile the pipeline template."""
        self._env = _make_env()
        self._template = self._env.from_string(_PIPELINE_TEMPLATE)

    def assemble(
        self,
        blocks: list[GeneratedBlock],
        macro_vars: list[MacroVar] | None = None,
    ) -> str:
        """Render all *blocks* into a single Python source string.

        Translatable blocks are rendered in the order given (caller is
        responsible for dependency ordering).  Untranslatable blocks are
        rendered in-place so engineers see exactly where manual work is needed.

        Args:
            blocks: Translated blocks from LLMClient, in dependency order.
            macro_vars: Optional list of macro variable constants to prepend as
                a constants section before the imports.

        Returns:
            Complete Python source ready to be saved as ``pipeline.py``.
        """
        source_files = sorted({b.source_block.source_file for b in blocks})
        entries = [_BlockEntry(header=_block_header(b), block=b) for b in blocks]
        return str(
            self._template.render(
                generated_at=datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
                source_files=source_files,
                entries=entries,
                constants=macro_vars or [],
            )
        )
