"""Code generator — assembles GeneratedBlocks into per-module Python files and a pipeline.

Uses Jinja2 for the file-level templates so the header and block stitching are
clearly separated from the translation logic.  The multi-file output:

- Emits one Python module per source SAS file (e.g. ``etl.sas`` → ``etl.py``)
- Each module wraps its blocks in a ``def run(dataframes: dict) -> dict:`` function
- Emits a ``pipeline.py`` that imports every module and threads ``dataframes`` through
- Starts each module with a provenance header listing all source files
- Includes necessary imports (pandas)
- Renders each block in dependency order with its ``# SAS: <file>:<line>``
  provenance comment already embedded by the LLM
- Wraps untranslatable blocks in a clearly labelled comment section

For backward compatibility (reconciliation, DB storage) ``assemble_flat()`` returns
the classic single-string concatenation.
"""

import os
from dataclasses import dataclass
from datetime import UTC, datetime

from jinja2 import Environment, StrictUndefined
from src.worker.engine.models import GeneratedBlock, MacroVar

# SAS: codegen.py:1

# ── Jinja2 templates ──────────────────────────────────────────────────────────

_MODULE_TEMPLATE = """\
# Generated by Rosetta Decode — {{ generated_at }}
# Source file: {{ sas_source_file }}
#
# WARNING: Review all # SAS-UNTRANSLATABLE sections before running in production.
{% if uncertain %}# UNCERTAIN blocks present — human review required
{% endif %}
{% if constants %}
# ── Macro constants ──────────────────────────────────────────────────────────
{% for c in constants %}
{{ c.name }} = {{ c.raw_value | macro_val }}  # SAS: {{ c.source_file }}:{{ c.line }}
{% endfor %}
{% endif %}


def run(dataframes: dict) -> dict:
{% for entry in entries %}
    # ── {{ entry.header }}
{% if entry.block.is_untranslatable %}
    # ┌─ UNTRANSLATABLE ────────────────────────────────────────────────────────┐
{{ entry.block.python_code | indent(4, first=True) }}
    # └────────────────────────────────────────────────────────────────────────┘
{% else %}
{{ entry.block.python_code | indent(4, first=True) }}
{% endif %}
{% endfor %}
    return dataframes
"""

_PIPELINE_TEMPLATE = """\
# Generated pipeline — do not edit manually
from . import {{ module_names | join(", ") }}


def run(dataframes: dict) -> dict:
{% for mod in module_names %}
    dataframes = {{ mod }}.run(dataframes)
{% endfor %}
    return dataframes
"""

_FLAT_TEMPLATE = """\
# Generated by Rosetta Decode — {{ generated_at }}
# Source files: {{ source_files | join(", ") }}
#
# WARNING: Review all # SAS-UNTRANSLATABLE sections before running in production.
{% if constants %}

# ── Macro constants ──────────────────────────────────────────────────────────
{% for c in constants %}
{{ c.name }} = {{ c.raw_value | macro_val }}  # SAS: {{ c.source_file }}:{{ c.line }}
{% endfor %}
{% endif %}
{% for entry in entries %}

# ── {{ entry.header }}
{% if entry.block.is_untranslatable %}
# ┌─ UNTRANSLATABLE ────────────────────────────────────────────────────────┐
{{ entry.block.python_code }}
# └────────────────────────────────────────────────────────────────────────┘
{% else %}
{{ entry.block.python_code }}
{% endif %}
{% endfor %}
"""


@dataclass
class _BlockEntry:
    """Pairs a GeneratedBlock with a pre-computed single-line header."""

    header: str
    block: GeneratedBlock


def _macro_val_filter(v: str) -> object:
    """Convert a SAS raw macro value to a valid Python literal.

    Args:
        v: The raw macro variable value string.

    Returns:
        An int, float, or repr'd string suitable for rendering as a Python literal.
    """
    stripped = v.strip()
    try:
        return int(stripped)
    except ValueError:
        pass
    try:
        return float(stripped)
    except ValueError:
        pass
    return repr(stripped)


def _make_env() -> Environment:
    """Return a Jinja2 environment with strict undefined checking."""
    env = Environment(undefined=StrictUndefined, keep_trailing_newline=True)
    env.filters["macro_val"] = _macro_val_filter
    return env


def _block_header(block: GeneratedBlock) -> str:
    """Build the one-line section header for a block.

    Args:
        block: The generated block to label.

    Returns:
        Header string in the form ``TYPE — file:line``.
    """
    sb = block.source_block
    return f"{sb.block_type.value} — {sb.source_file}:{sb.start_line}"


def _sas_to_module_name(source_file: str) -> str:
    """Derive a Python module name from a SAS filename.

    Strips directory components and the ``.sas`` extension, then returns the
    stem.  E.g. ``subdir/etl.sas`` → ``etl``.

    Args:
        source_file: Raw ``source_file`` value from a ``SASBlock``.

    Returns:
        Python-safe module stem (basename without extension).
    """
    basename = os.path.basename(source_file)
    stem, _ = os.path.splitext(basename)
    return stem


# ── Public API ────────────────────────────────────────────────────────────────


class CodeGenerator:
    """Assembles a list of GeneratedBlocks into per-module Python files and a pipeline."""

    def __init__(self) -> None:
        """Initialise the Jinja2 environment and compile all templates."""
        self._env = _make_env()
        self._module_tmpl = self._env.from_string(_MODULE_TEMPLATE)
        self._pipeline_tmpl = self._env.from_string(_PIPELINE_TEMPLATE)
        self._flat_tmpl = self._env.from_string(_FLAT_TEMPLATE)

    def assemble(
        self,
        blocks: list[GeneratedBlock],
        macro_vars: list[MacroVar] | None = None,
    ) -> dict[str, str]:
        """Render *blocks* into a dict of Python module sources keyed by filename.

        Groups blocks by their originating SAS file.  Each group becomes a
        ``<stem>.py`` module with a ``run(dataframes: dict) -> dict:`` function.
        A ``pipeline.py`` entry is also emitted that imports all modules in
        first-seen order and threads ``dataframes`` through them sequentially.

        If any block in a module has ``confidence != "high"``, the module header
        will contain: ``# UNCERTAIN blocks present — human review required``.

        Args:
            blocks: Translated blocks from LLMClient, in dependency order.
            macro_vars: Optional list of macro variable constants to prepend as
                a constants section in each module.

        Returns:
            Mapping of ``filename.py`` → Python source string, plus
            ``"pipeline.py"`` as an additional entry.
        """
        generated_at = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
        mvars = macro_vars or []

        # Preserve first-seen insertion order across source files.
        grouped: dict[str, list[GeneratedBlock]] = {}
        for block in blocks:
            key = block.source_block.source_file
            grouped.setdefault(key, []).append(block)

        result: dict[str, str] = {}
        module_names: list[str] = []

        for sas_file, file_blocks in grouped.items():
            mod_name = _sas_to_module_name(sas_file)
            module_names.append(mod_name)
            uncertain = any(b.confidence != "high" for b in file_blocks)
            entries = [_BlockEntry(header=_block_header(b), block=b) for b in file_blocks]
            source = str(
                self._module_tmpl.render(
                    generated_at=generated_at,
                    sas_source_file=sas_file,
                    uncertain=uncertain,
                    entries=entries,
                    constants=mvars,
                )
            )
            result[f"{mod_name}.py"] = source

        result["pipeline.py"] = str(self._pipeline_tmpl.render(module_names=module_names))
        return result

    def assemble_flat(
        self,
        blocks: list[GeneratedBlock],
        macro_vars: list[MacroVar] | None = None,
    ) -> str:
        """Render all *blocks* into a single concatenated Python source string.

        This is the legacy single-file format used for reconciliation execution
        and the ``python_code`` database column.  The output is equivalent to
        the pre-multi-file ``assemble()`` behaviour.

        Args:
            blocks: Translated blocks from LLMClient, in dependency order.
            macro_vars: Optional list of macro variable constants to prepend.

        Returns:
            Complete Python source ready to be saved as a single ``pipeline.py``.
        """
        source_files = sorted({b.source_block.source_file for b in blocks})
        entries = [_BlockEntry(header=_block_header(b), block=b) for b in blocks]
        rendered = str(
            self._flat_tmpl.render(
                generated_at=datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
                source_files=source_files,
                entries=entries,
                constants=macro_vars or [],
            )
        )
        last_output_var: str | None = None
        for block in reversed(blocks):
            if block.output_var is not None:
                last_output_var = block.output_var
                break
        if last_output_var is not None:
            rendered += f"\nresult = {last_output_var}\n"
        return rendered
