import type { JobPlanResponse, TrustReportResponse } from "@/api/types";
import { Button } from "@/components/ui/button";
import { AlertTriangle, ChevronDown, ChevronRight } from "lucide-react";
import React, { useState } from "react";
import { toast } from "sonner";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface Props {
  trustReport: TrustReportResponse;
  planData: JobPlanResponse;
  jobName: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatDate(d: Date): string {
  const day = String(d.getDate()).padStart(2, "0");
  const month = d.toLocaleString("en-GB", { month: "short" });
  const year = d.getFullYear();
  return `${day} ${month} ${year}`;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function BeforeYouAcceptPanel({
  trustReport,
  planData,
  jobName,
}: Props): React.ReactElement {
  const [panelOpen, setPanelOpen] = useState(true);
  const [disclosureOpen, setDisclosureOpen] = useState(false);

  // Derived values
  const total =
    trustReport.auto_verified +
    trustReport.needs_review +
    trustReport.manual_todo +
    trustReport.failed_reconciliation;
  const reviewCount =
    trustReport.needs_review +
    trustReport.manual_todo +
    trustReport.failed_reconciliation;
  const estimatedHours =
    trustReport.needs_review * 1 +
    trustReport.manual_todo * 4 +
    trustReport.failed_reconciliation * 2;
  const confidencePct = Math.round((trustReport.overall_confidence_score ?? 0) * 100);

  function handleCopy(): void {
    const reviewLine =
      reviewCount > 0
        ? `${reviewCount} steps require manual review before acceptance (~${estimatedHours}h estimated).`
        : "No manual review required.";

    const text = [
      `${jobName} — migration readiness summary`,
      "",
      `${trustReport.auto_verified} of ${total} steps translated automatically.`,
      reviewLine,
      "",
      `Risk level: ${planData.overall_risk}`,
      `Automated confidence: ${confidencePct}%`,
      "",
      `Generated by Rosetta · ${formatDate(new Date())}`,
    ].join("\n");

    navigator.clipboard.writeText(text).then(() => {
      toast.success("Summary copied to clipboard.");
    });
  }

  return (
    <div className="border border-border rounded-lg px-4 py-3 space-y-2">
      {/* Header row */}
      <div className="flex items-center justify-between">
        <button
          type="button"
          onClick={() => setPanelOpen((v) => !v)}
          className="flex items-center gap-2 cursor-pointer hover:opacity-80 transition-opacity"
          aria-expanded={panelOpen}
        >
          {panelOpen ? (
            <ChevronDown size={14} className="text-muted-foreground shrink-0" />
          ) : (
            <ChevronRight size={14} className="text-muted-foreground shrink-0" />
          )}
          <h2 className="text-sm font-semibold text-foreground">Before you accept</h2>
        </button>
        <Button size="sm" variant="outline" onClick={handleCopy}>
          Copy summary
        </Button>
      </div>

      {/* Collapsible body */}
      {panelOpen && (
        <div className="space-y-2 pl-5">
          {/* Headline */}
          <p className="text-sm text-muted-foreground">
            {trustReport.auto_verified} of {total} steps translated automatically — no action
            needed.
          </p>

          {reviewCount > 0 ? (
            <>
              {/* Review line */}
              <p className="text-sm text-foreground">
                {reviewCount} step{reviewCount === 1 ? "" : "s"} require manual review before you
                can accept with confidence. Estimated effort: ~{estimatedHours}h. See Needs
                attention ↑ for the full list.
              </p>

              {/* Risk warning */}
              <div className="flex items-start gap-2 rounded-md bg-amber-50 border border-amber-200 px-3 py-2 text-xs text-amber-800">
                <AlertTriangle size={14} className="shrink-0 mt-0.5" aria-hidden />
                <span>
                  Accepting without reviewing these steps means relying on automated translation for
                  logic the tool flagged as uncertain.
                </span>
              </div>
            </>
          ) : (
            /* Green confirmation */
            <p className="text-sm text-emerald-700">
              All steps translated automatically. No manual work required before accepting.
            </p>
          )}

          {/* "How is this estimated?" disclosure */}
          <div>
            <button
              type="button"
              onClick={() => setDisclosureOpen((v) => !v)}
              className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
              aria-expanded={disclosureOpen}
            >
              {disclosureOpen ? (
                <ChevronDown size={12} className="shrink-0" />
              ) : (
                <ChevronRight size={12} className="shrink-0" />
              )}
              How is this estimated?
            </button>

            {disclosureOpen && (
              <pre className="text-xs text-muted-foreground mt-2 font-mono leading-relaxed whitespace-pre-wrap">
                {[
                  `Needs review    × 1h = ${trustReport.needs_review}h`,
                  `Manual TODO     × 4h = ${trustReport.manual_todo * 4}h  (requires a developer)`,
                  `Failed recon    × 2h = ${trustReport.failed_reconciliation * 2}h`,
                  `─────────────────────`,
                  `Total           ~${estimatedHours}h`,
                  ``,
                  `Rates reflect typical review complexity. Steps with higher criticality may take longer.`,
                ].join("\n")}
              </pre>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
