/* 06_build_edd_queue.sas
   Build EDD work queue and produce periodic review report.
   L. Fernandez / Compliance Reporting  2022-09-01
*/

%m_log_step(STEP_NAME=06_build_edd_queue);

/* Identify clients requiring Enhanced Due Diligence */
DATA work.edd_queue;
  SET work.clients_scored;

  /* EDD trigger conditions */
  edd_trigger_high   = (crr_band_cd = 'HIGH');
  edd_trigger_pep    = (pep_flag IN ('Y', 'P'));
  edd_trigger_sanc   = (match_flg = 'Y' AND match_method = 'COMPGED');
  edd_trigger_cntry  = (INPUT(cntry_resdnc_cd, CNTRY_RISK_IN.) >= 4);

  edd_required = (edd_trigger_high OR edd_trigger_pep OR edd_trigger_sanc OR edd_trigger_cntry);

  IF edd_required THEN DO;
    /* Assign case priority */
    IF match_flg = 'Y' AND edd_trigger_sanc THEN case_priority = 1;  /* Sanctions — urgent */
    ELSE IF pep_flag = 'Y'                  THEN case_priority = 2;  /* Confirmed PEP */
    ELSE IF crr_band_cd = 'HIGH'            THEN case_priority = 3;  /* High risk band */
    ELSE                                         case_priority = 4;  /* Other EDD trigger */

    /* Build reason text */
    edd_reason_txt = CATX('; ',
      IFC(edd_trigger_sanc,   'Sanctions near-match', ''),
      IFC(pep_flag = 'Y',     'Confirmed PEP',        ''),
      IFC(pep_flag = 'P',     'Possible PEP',         ''),
      IFC(edd_trigger_high AND NOT edd_trigger_sanc AND pep_flag = 'N',
                              'High CRR score',        ''),
      IFC(edd_trigger_cntry,  'High-risk jurisdiction', '')
    );
    edd_reason_txt = COMPBL(edd_reason_txt);

    OUTPUT;
  END;

RUN;

PROC SORT DATA=work.edd_queue;
  BY case_priority crr_score DESCENDING;
RUN;

/* Write EDD queue to output library */
DATA OUTLIB.edd_work_queue;
  SET work.edd_queue;
RUN;

/* TODO: remove before prod */
PROC PRINT DATA=work.edd_queue (OBS=10);
  TITLE "DEBUG: EDD Queue sample — AS_OF_DT=&AS_OF_DT.";
  VAR cust_id full_nm_display crr_band_cd crr_score case_priority edd_reason_txt;
RUN;

/* Clients past their periodic review due date */
DATA work.review_due;
  SET work.client_master_scd;
  WHERE curr_flg = 'Y';

  /* Compare last_review_dt against band-specific cutoff */
  IF crr_band_cd = 'HIGH' AND last_review_dt < &REVIEW_CUTOFF_HIGH. THEN review_due_flg = 'Y';
  ELSE IF crr_band_cd = 'MED' AND last_review_dt < &REVIEW_CUTOFF_MED. THEN review_due_flg = 'Y';
  ELSE IF crr_band_cd = 'LOW' AND last_review_dt < &REVIEW_CUTOFF_LOW. THEN review_due_flg = 'Y';
  ELSE review_due_flg = 'N';

  IF review_due_flg = 'Y';
RUN;

/* Periodic review report via PROC REPORT + ODS */
ODS RTF FILE="\\mer-sas-prod\reports\kyc_periodic_review_&AS_OF_DT..rtf"
        STYLE=JOURNAL;

PROC REPORT DATA=work.review_due NOWD HEADLINE;
  TITLE "Meridian Asset Partners — Periodic KYC Review Due Report";
  TITLE2 "As of &AS_OF_DT. — Generated by FinCrime Batch";

  COLUMN cust_id full_nm_std crr_band_cd crr_score last_review_dt;

  DEFINE cust_id        / DISPLAY 'Client ID';
  DEFINE full_nm_std    / DISPLAY 'Client Name';
  DEFINE crr_band_cd    / DISPLAY 'Risk Band';
  DEFINE crr_score      / DISPLAY 'CRR Score' FORMAT=BEST8.;
  DEFINE last_review_dt / DISPLAY 'Last Review' FORMAT=DATE9.;

  COMPUTE crr_band_cd / CHARACTER LENGTH=4;
    IF crr_band_cd = 'HIGH' THEN
      CALL DEFINE(_COL_, 'STYLE', 'STYLE=[BACKGROUND=SALMON]');
  ENDCOMP;

RUN;

ODS RTF CLOSE;

%PUT NOTE: [06_build_edd_queue] EDD queue: %SYSFUNC(attrn(%SYSFUNC(open(work.edd_queue)),NOBS)) cases.;
%PUT NOTE: [06_build_edd_queue] Review due: %SYSFUNC(attrn(%SYSFUNC(open(work.review_due)),NOBS)) clients.;
